
# Cover states
- platform: template
  sensors:
    diningroom_state:
        value_template: "{{ states.cover.diningroom.state }}"
        friendly_name: 'HAS state'
    diningroom_elero_state:
        value_template: "{{ state_attr('cover.diningroom', 'elero_state') }}"
        friendly_name: 'Elero state'
    diningroom_current_position:
        value_template: "{{state_attr('cover.diningroom', 'current_position')}}"
        friendly_name: 'HA position'
    diningroom_current_tilt_position:
        value_template: "{{state_attr('cover.diningroom', 'current_tilt_position')}}"
        friendly_name: 'HA tilt position'
